command:
  - uvicorn
  - API.src.main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: PYTHONPATH
    value: "."
  - name: CONFIG_DIR
    value: "config"
  - name: USE_POSTGRES
    value: "true"
  - name: POSTGRES_BACKEND
    value: "lakebase"
  - name: POSTGRES_LAKEBASE_ENDPOINT
    valueFrom: postgres
  - name: USE_LOCAL_DATA
    value: "true"
  - name: LOCAL_DATA_PATH
    value: "data/sample_job_metrics.csv"
  - name: USE_MOCK_LLM
    value: "true"
  - name: APP_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "INFO"
  - name: AZURE_OPENAI_ENDPOINT
    value: "https://project_name.services.ai.azure.com"
  - name: AZURE_OPENAI_DEPLOYMENT_NAME
    value: "model-name"
  - name: FAISS_VOLUME_ROOT
    valueFrom: faiss-volume
  - name: FAISS_INDEX_PATH
    value: "/Volumes/../faiss_index"
  - name: DATABRICKS_HOST
    value: "adb-1234567890.1.azuredatabricks.net"
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/<id>"
  - name: DATABRICKS_SERVICE_CREDENTIAL_NAME
    value: "project_name-service-cred-name"
