#!/usr/bin/env bash
# Package and deploy Insights Hub UI (Angular) to Databricks Apps.
#
# Prerequisites:
#   - API Databricks App deployed and Running
#   - databricks CLI authenticated (databricks auth login)
#   - Node 18+ and npm
#
# Usage:
#   API_PROXY_TARGET=https://your-api-app.databricksapps.com \
#   WORKSPACE_USER=you@company.com \
#   ./scripts/deploy-databricks-ui.sh
#
# Optional environment variables:
#   API_PROXY_TARGET         Base URL of the FastAPI Databricks App (required unless set in UI/app.yaml)
#   WORKSPACE_USER           Workspace user email for default sync path
#   UI_WS_PATH               Workspace folder (default: /Workspace/Users/${WORKSPACE_USER}/edim-dde-ai-agents-ui)
#   DATABRICKS_UI_APP_NAME   App name (default: edim-dde-ai-agents-ui)
#   DATABRICKS_PROFILE       CLI profile passed as -p to databricks commands
#   SKIP_BUILD=1             Skip npm ci && npm run build
#   SKIP_SYNC=1              Skip databricks sync (deploy only)
#   CREATE_APP=1             Run databricks apps create if the app does not exist
#   CLEAN_WORKSPACE=1          Delete entire workspace folder before sync (default: 0 — preserves ACLs)
#   CLEAN_STALE_FILES=1        Delete server.js/app.yaml/etc. before sync (default: 0 — sync overwrites)
#   CLEAN_NODE_MODULES=1       Delete workspace node_modules after sync, before deploy (default: 0)
#   DEPLOY_MODE=slim|full      slim = minimal runtime bundle (default); full = sync entire UI/
#
# Examples:
#   CREATE_APP=1 API_PROXY_TARGET=https://... WORKSPACE_USER=me@co.com ./scripts/deploy-databricks-ui.sh
#   DEPLOY_MODE=full SKIP_BUILD=1 ./scripts/deploy-databricks-ui.sh   # after manual ng build
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UI_DIR="${ROOT}/UI"
STAGING_DIR="${ROOT}/deploy/databricks-ui"

APP_NAME="${DATABRICKS_UI_APP_NAME:-edim-dde-ai-agents-ui}"
DEPLOY_MODE="${DEPLOY_MODE:-slim}"
SKIP_BUILD="${SKIP_BUILD:-0}"
SKIP_SYNC="${SKIP_SYNC:-0}"
CREATE_APP="${CREATE_APP:-0}"

usage() {
  sed -n '2,28p' "$0" | sed 's/^# \?//'
  exit "${1:-0}"
}

log() { printf '==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

databricks_cmd() {
  # Git Bash on Windows rewrites /Workspace/... → C:/Program Files/Git/Workspace/...
  # Disable MSYS path conversion for all databricks CLI calls.
  if [[ -n "${MSYSTEM:-}" || "${OSTYPE:-}" == msys* ]]; then
    MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' \
      databricks ${DATABRICKS_PROFILE:+-p "$DATABRICKS_PROFILE"} "$@"
    return
  fi
  if [[ -n "${DATABRICKS_PROFILE:-}" ]]; then
    databricks -p "${DATABRICKS_PROFILE}" "$@"
  else
    databricks "$@"
  fi
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

normalize_api_url() {
  local url="${1%/}"
  url="${url%/api}"
  printf '%s' "$url"
}

read_api_target_from_app_yaml() {
  local yaml_file="$1"
  [[ -f "$yaml_file" ]] || return 1
  local line
  line="$(grep -E '^\s*value:\s*"https?://' "$yaml_file" | head -1 || true)"
  [[ -n "$line" ]] || return 1
  line="${line#*value: \"}"
  line="${line%\"*}"
  if [[ "$line" == *REPLACE* ]]; then
    return 1
  fi
  printf '%s' "$line"
}

write_app_yaml() {
  local dest="$1"
  local api_target="$2"
  cat >"$dest" <<EOF
# Generated by scripts/deploy-databricks-ui.sh — do not edit on workspace; redeploy from repo.
command:
  - node
  - server.js

env:
  - name: NODE_ENV
    value: production
  - name: API_PROXY_TARGET
    value: "${api_target}"
EOF
}

write_runtime_package_json() {
  local dest="$1"
  cat >"$dest" <<'EOF'
{
  "name": "cluster-advisor-ui-runtime",
  "private": true,
  "version": "1.0.0",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "engines": {
    "node": ">=18"
  },
  "dependencies": {
    "express": "4.21.2"
  }
}
EOF
}

write_deploy_manifest() {
  local dest="$1"
  local api_target="$2"
  cat >"$dest" <<EOF
deployed_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
server_proxy=native-http-https
express_only=true
api_proxy_target=${api_target}
EOF
}

verify_local_server() {
  if grep -qE "require\(['\"]http-proxy-middleware['\"]\)" "${UI_DIR}/server.js"; then
    die "UI/server.js still requires http-proxy-middleware. Run: git pull (you need the native http/https proxy version)."
  fi
  if ! grep -q "require('http')" "${UI_DIR}/server.js"; then
    die "UI/server.js does not look like the fixed Databricks runtime server."
  fi
  log "Local UI/server.js OK (native proxy, no http-proxy-middleware require)"
}

verify_staging_bundle() {
  local dir="$1"
  if grep -qE "require\(['\"]http-proxy-middleware['\"]\)" "${dir}/server.js"; then
    die "Staging server.js still requires http-proxy-middleware. Git pull latest UI/server.js."
  fi
  if grep -q 'http-proxy-middleware' "${dir}/package.json"; then
    die "Staging package.json still lists http-proxy-middleware."
  fi
  if ! grep -q "require('http')" "${dir}/server.js"; then
    die "Staging server.js missing native http/https proxy — wrong file?"
  fi
  log "Staging bundle verified (native proxy, express-only package.json)"
}

cleanup_stale_runtime_files() {
  local ws_path="$1"
  log "Removing stale runtime files before sync: ${ws_path}"
  local f
  for f in server.js app.yaml package.json DEPLOY_MANIFEST.txt package-lock.json; do
    databricks_cmd workspace delete "${ws_path}/${f}" 2>/dev/null || true
  done
  databricks_cmd workspace delete "${ws_path}/node_modules" --recursive 2>/dev/null || true
  log "Stale runtime files cleared"
}

cleanup_workspace_node_modules() {
  local ws_path="$1"
  if [[ "${CLEAN_NODE_MODULES:-0}" != "1" ]]; then
    return 0
  fi
  log "Removing workspace node_modules (stale deps) after sync: ${ws_path}/node_modules"
  databricks_cmd workspace delete "${ws_path}/node_modules" --recursive 2>/dev/null || true
}

cleanup_workspace_folder() {
  local ws_path="$1"
  if [[ "${CLEAN_WORKSPACE:-0}" == "1" ]]; then
    log "WARNING: Deleting entire workspace folder — re-grant app service principal access after sync."
    log "Removing workspace folder: ${ws_path}"
    databricks_cmd workspace delete "${ws_path}" --recursive 2>/dev/null || true
    local listing
    if listing="$(databricks_cmd workspace list "${ws_path}" 2>/dev/null || true)"; then
      if [[ -n "${listing//[[:space:]]/}" ]]; then
        die "Workspace folder still exists after delete: ${ws_path}"
      fi
    fi
    log "Workspace folder cleared"
    return 0
  fi
  if [[ "${CLEAN_STALE_FILES:-0}" == "1" ]]; then
    cleanup_stale_runtime_files "${ws_path}"
  else
    log "No pre-sync cleanup (sync --full overwrites files in place; folder ACLs preserved)"
  fi
}

sync_to_workspace() {
  local sync_source="$1"
  local ws_path="$2"
  log "Syncing ${sync_source} -> ${ws_path}"
  local sync_out
  # Slim staging bundle has no node_modules/.git — skip --exclude (some CLI versions mishandle it).
  local sync_args=(sync "${sync_source}" "${ws_path}")
  if [[ "${DEPLOY_MODE}" == "full" ]]; then
    sync_args+=(--exclude node_modules --exclude .git --exclude .angular)
  fi
  if ! sync_out="$(databricks_cmd "${sync_args[@]}" --full 2>&1)"; then
    log "Retrying sync without --full (older CLI)"
    sync_out="$(databricks_cmd "${sync_args[@]}" 2>&1)" || die "Sync failed:\n${sync_out}"
  fi
  printf '%s\n' "${sync_out}" | tail -10
}

workspace_file_exists() {
  local ws_file="$1"
  databricks_cmd workspace get-status "${ws_file}" >/dev/null 2>&1
}

verify_workspace_folder() {
  local ws_path="$1"
  log "Verifying workspace upload: ${ws_path}"
  local missing=()
  local f
  for f in server.js app.yaml package.json; do
    if ! workspace_file_exists "${ws_path}/${f}"; then
      missing+=("${f}")
    fi
  done
  if [[ ${#missing[@]} -eq 0 ]]; then
    log "Workspace has server.js, app.yaml, package.json"
    return 0
  fi
  local listing
  listing="$(databricks_cmd workspace list "$ws_path" 2>&1 || true)"
  die "Missing on workspace after sync: ${missing[*]}
Path: ${ws_path}
Listing:
${listing}
If manual sync works but this script fails, run from PowerShell (not Git Bash) or set SKIP_SYNC=1 after syncing manually."
}

verify_deployed_server() {
  local ws_path="$1"
  local tmp export_err
  tmp="$(mktemp)"
  if ! export_err="$(databricks_cmd workspace export "${ws_path}/server.js" "${tmp}" 2>&1)"; then
    rm -f "${tmp}"
    die "Could not export ${ws_path}/server.js after sync.
CLI output: ${export_err}
Common causes:
  - WORKSPACE_USER email does not match the workspace path owner
  - Sync uploaded to a different path (Git Bash path mangling — use PowerShell)
  - Folder is empty — run: databricks workspace list \"${ws_path}\""
  fi
  if grep -qE "require\(['\"]http-proxy-middleware['\"]\)" "${tmp}"; then
    rm -f "${tmp}"
    die "Workspace server.js is STILL the old version after sync.
1. In Databricks Workspace UI, delete folder: ${ws_path}
2. Confirm the app deploys from workspace (Apps → Deploy → From workspace), not Git with an old branch
3. Re-run with CLEAN_WORKSPACE=1"
  fi
  if ! grep -q "require('http')" "${tmp}"; then
    rm -f "${tmp}"
    die "Workspace server.js missing native http/https proxy — wrong file uploaded?"
  fi
  log "Verified workspace server.js (native proxy, no http-proxy-middleware)"
  rm -f "${tmp}"
}

verify_deploy_manifest() {
  local ws_path="$1"
  local tmp
  tmp="$(mktemp)"
  if databricks_cmd workspace export "${ws_path}/DEPLOY_MANIFEST.txt" "${tmp}" 2>/dev/null; then
    if grep -q 'server_proxy=native-http-https' "${tmp}"; then
      log "Verified DEPLOY_MANIFEST.txt (native-http-https)"
    else
      log "Warning: DEPLOY_MANIFEST.txt present but missing server_proxy=native-http-https"
    fi
  else
    log "Warning: DEPLOY_MANIFEST.txt not found on workspace (slim deploy may be from older script)"
  fi
  rm -f "${tmp}"
}

print_git_source_warning() {
  cat <<EOF

If deploy still crashes with http-proxy-middleware AFTER verify passed:
  The app may be deploying from **Git**, not the workspace folder you synced.
  Apps → ${APP_NAME} → check Source / Deploy:
    - Use "From workspace" and path: ${UI_WS_PATH}
    - OR push the fixed UI/server.js to the Git branch the app uses
    - If workspace requires Git-only deploys, you must push the fix to Git

EOF
}

prepare_slim_bundle() {
  local api_target="$1"
  log "Preparing slim deploy bundle at ${STAGING_DIR}"
  rm -rf "${STAGING_DIR}"
  mkdir -p "${STAGING_DIR}/dist/cluster-advisor-ui"

  [[ -f "${UI_DIR}/dist/cluster-advisor-ui/index.html" ]] \
    || die "Missing ${UI_DIR}/dist/cluster-advisor-ui/index.html — run build first (or unset SKIP_BUILD)"

  cp "${UI_DIR}/server.js" "${STAGING_DIR}/"
  cp -R "${UI_DIR}/dist/cluster-advisor-ui/." "${STAGING_DIR}/dist/cluster-advisor-ui/"

  write_app_yaml "${STAGING_DIR}/app.yaml" "$api_target"
  write_runtime_package_json "${STAGING_DIR}/package.json"
  write_deploy_manifest "${STAGING_DIR}/DEPLOY_MANIFEST.txt" "$api_target"

  # Do not sync node_modules — Databricks runs npm install from package.json on deploy.
  # Syncing node_modules can leave stale http-proxy-middleware from older bundles.
  cat >"${STAGING_DIR}/.gitignore" <<'EOF'
node_modules
EOF

  verify_staging_bundle "${STAGING_DIR}"
}

prepare_full_sync_path() {
  local api_target="$1"
  [[ -f "${UI_DIR}/dist/cluster-advisor-ui/index.html" ]] \
    || die "Missing UI build output — run build first (or unset SKIP_BUILD)"

  if [[ -n "${API_PROXY_TARGET:-}" ]]; then
    log "Writing API_PROXY_TARGET into ${UI_DIR}/app.yaml for full sync"
    write_app_yaml "${UI_DIR}/app.yaml" "$api_target"
  fi

  printf '%s' "${UI_DIR}"
}

ensure_app_exists() {
  if databricks_cmd apps get "$APP_NAME" >/dev/null 2>&1; then
    log "Databricks app '${APP_NAME}' already exists"
    return 0
  fi
  if [[ "${CREATE_APP}" != "1" ]]; then
    die "App '${APP_NAME}' not found. Create it in the workspace UI or re-run with CREATE_APP=1"
  fi
  log "Creating Databricks app '${APP_NAME}'"
  databricks_cmd apps create "$APP_NAME"
}

print_sp_permission_hint() {
  local ws_path="$1"
  cat <<EOF

If deploy fails with "no files found" or Service Principal access:
  1. Open Compute → Apps → ${APP_NAME} → Environment tab
  2. Note the app service principal (client id / name)
  3. Grant access on the **parent folder** so it survives redeploys:
       /Workspace/Users/<your-email>/
     (Can Read is enough; Can Manage also works)
  4. Or grant on the app folder: ${ws_path}
  5. Re-run deploy (SKIP_BUILD=1 SKIP_SYNC=1 if files are already synced)

Avoid CLEAN_WORKSPACE=1 unless necessary — deleting the folder removes ACLs you set on it.

EOF
}

main() {
  case "${1:-}" in
    -h|--help) usage 0 ;;
  esac

  require_cmd databricks
  require_cmd node
  require_cmd npm

  [[ -d "${UI_DIR}" ]] || die "UI directory not found: ${UI_DIR}"
  verify_local_server

  local api_target="${API_PROXY_TARGET:-}"
  if [[ -z "$api_target" ]]; then
    api_target="$(read_api_target_from_app_yaml "${UI_DIR}/app.yaml" || true)"
  fi
  [[ -n "$api_target" ]] || die "Set API_PROXY_TARGET to your FastAPI Databricks App URL (no trailing slash)"
  api_target="$(normalize_api_url "$api_target")"

  if [[ -z "${UI_WS_PATH:-}" ]]; then
    [[ -n "${WORKSPACE_USER:-}" ]] \
      || die "Set WORKSPACE_USER or UI_WS_PATH for the workspace sync destination"
    UI_WS_PATH="/Workspace/Users/${WORKSPACE_USER}/${APP_NAME}"
  fi
  # Normalize: must be a Databricks workspace path, not a Git-Bash-mangled local path
  if [[ "${UI_WS_PATH}" == *"/Program Files/Git/Workspace/"* ]]; then
    UI_WS_PATH="/Workspace/${UI_WS_PATH#*/Program Files/Git/Workspace/}"
    log "Corrected Git Bash workspace path to: ${UI_WS_PATH}"
  fi
  if [[ "${UI_WS_PATH}" != /Workspace/* ]]; then
    die "UI_WS_PATH must start with /Workspace/ (got: ${UI_WS_PATH}). On Git Bash use PowerShell or re-run this script (MSYS path fix is applied)."
  fi

  log "App name:        ${APP_NAME}"
  log "API proxy target: ${api_target}"
  log "Workspace path:  ${UI_WS_PATH}"
  log "Deploy mode:     ${DEPLOY_MODE}"

  if [[ "${SKIP_BUILD}" != "1" ]]; then
    log "Building Angular UI (npm ci && npm run build)"
    (cd "${UI_DIR}" && npm ci && npm run build)
  else
    log "Skipping UI build (SKIP_BUILD=1)"
  fi

  local sync_source
  case "${DEPLOY_MODE}" in
    slim)
      prepare_slim_bundle "$api_target"
      sync_source="${STAGING_DIR}"
      ;;
    full)
      sync_source="$(prepare_full_sync_path "$api_target")"
      ;;
    *)
      die "Invalid DEPLOY_MODE=${DEPLOY_MODE} (use slim or full)"
      ;;
  esac

  ensure_app_exists

  cleanup_workspace_folder "${UI_WS_PATH}"

  if [[ "${SKIP_SYNC}" != "1" ]]; then
    sync_to_workspace "${sync_source}" "${UI_WS_PATH}"
    cleanup_workspace_node_modules "${UI_WS_PATH}"
  else
    log "Skipping sync (SKIP_SYNC=1) — using files already on workspace"
  fi

  verify_workspace_folder "${UI_WS_PATH}"
  verify_deployed_server "${UI_WS_PATH}"
  verify_deploy_manifest "${UI_WS_PATH}"
  print_git_source_warning
  print_sp_permission_hint "${UI_WS_PATH}"

  log "Deploying Databricks app '${APP_NAME}' (SNAPSHOT from workspace)"
  databricks_cmd apps deploy "$APP_NAME" \
    --source-code-path "${UI_WS_PATH}" \
    --mode SNAPSHOT

  log "Done. Check status and URL:"
  printf '  databricks apps get %s\n' "$APP_NAME"
  printf '  databricks apps logs %s\n' "$APP_NAME"
}

main "$@"
