#!/usr/bin/env bash
# Package and deploy Insights Hub UI (Angular) to Databricks Apps.
#
# Prerequisites:
#   - API Databricks App deployed and Running
#   - databricks CLI authenticated (databricks auth login)
#   - Node 18+ and npm
#
# Usage:
#   API_PROXY_TARGET=https://your-api-app.databricksapps.com \
#   WORKSPACE_USER=you@company.com \
#   ./scripts/deploy-databricks-ui.sh
#
# Optional environment variables:
#   API_PROXY_TARGET         Base URL of the FastAPI Databricks App (required unless set in UI/app.yaml)
#   WORKSPACE_USER           Workspace user email for default sync path
#   UI_WS_PATH               Workspace folder (default: /Workspace/Users/${WORKSPACE_USER}/edim-dde-ai-agents-ui)
#   DATABRICKS_UI_APP_NAME   App name (default: edim-dde-ai-agents-ui)
#   DATABRICKS_PROFILE       CLI profile passed as -p to databricks commands
#   SKIP_BUILD=1             Skip npm ci && npm run build
#   SKIP_SYNC=1              Skip databricks sync (deploy only)
#   CREATE_APP=1             Run databricks apps create if the app does not exist
#   DEPLOY_MODE=slim|full    slim = minimal runtime bundle (default); full = sync entire UI/
#
# Examples:
#   CREATE_APP=1 API_PROXY_TARGET=https://... WORKSPACE_USER=me@co.com ./scripts/deploy-databricks-ui.sh
#   DEPLOY_MODE=full SKIP_BUILD=1 ./scripts/deploy-databricks-ui.sh   # after manual ng build
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UI_DIR="${ROOT}/UI"
STAGING_DIR="${ROOT}/deploy/databricks-ui"

APP_NAME="${DATABRICKS_UI_APP_NAME:-edim-dde-ai-agents-ui}"
DEPLOY_MODE="${DEPLOY_MODE:-slim}"
SKIP_BUILD="${SKIP_BUILD:-0}"
SKIP_SYNC="${SKIP_SYNC:-0}"
CREATE_APP="${CREATE_APP:-0}"

usage() {
  sed -n '2,28p' "$0" | sed 's/^# \?//'
  exit "${1:-0}"
}

log() { printf '==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

databricks_cmd() {
  # Git Bash on Windows rewrites /Workspace/... → C:/Program Files/Git/Workspace/...
  # Disable MSYS path conversion for all databricks CLI calls.
  if [[ -n "${MSYSTEM:-}" || "${OSTYPE:-}" == msys* ]]; then
    MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' \
      databricks ${DATABRICKS_PROFILE:+-p "$DATABRICKS_PROFILE"} "$@"
    return
  fi
  if [[ -n "${DATABRICKS_PROFILE:-}" ]]; then
    databricks -p "${DATABRICKS_PROFILE}" "$@"
  else
    databricks "$@"
  fi
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

normalize_api_url() {
  local url="${1%/}"
  url="${url%/api}"
  printf '%s' "$url"
}

read_api_target_from_app_yaml() {
  local yaml_file="$1"
  [[ -f "$yaml_file" ]] || return 1
  local line
  line="$(grep -E '^\s*value:\s*"https?://' "$yaml_file" | head -1 || true)"
  [[ -n "$line" ]] || return 1
  line="${line#*value: \"}"
  line="${line%\"*}"
  if [[ "$line" == *REPLACE* ]]; then
    return 1
  fi
  printf '%s' "$line"
}

write_app_yaml() {
  local dest="$1"
  local api_target="$2"
  cat >"$dest" <<EOF
# Generated by scripts/deploy-databricks-ui.sh — do not edit on workspace; redeploy from repo.
command:
  - node
  - server.js

env:
  - name: NODE_ENV
    value: production
  - name: API_PROXY_TARGET
    value: "${api_target}"
EOF
}

write_runtime_package_json() {
  local dest="$1"
  cat >"$dest" <<'EOF'
{
  "name": "cluster-advisor-ui-runtime",
  "private": true,
  "version": "1.0.0",
  "dependencies": {
    "express": "^4.21.2",
    "http-proxy-middleware": "^3.0.3"
  }
}
EOF
}

prepare_slim_bundle() {
  local api_target="$1"
  log "Preparing slim deploy bundle at ${STAGING_DIR}"
  rm -rf "${STAGING_DIR}"
  mkdir -p "${STAGING_DIR}/dist/cluster-advisor-ui"

  [[ -f "${UI_DIR}/dist/cluster-advisor-ui/index.html" ]] \
    || die "Missing ${UI_DIR}/dist/cluster-advisor-ui/index.html — run build first (or unset SKIP_BUILD)"

  cp "${UI_DIR}/server.js" "${STAGING_DIR}/"
  cp -R "${UI_DIR}/dist/cluster-advisor-ui/." "${STAGING_DIR}/dist/cluster-advisor-ui/"

  write_app_yaml "${STAGING_DIR}/app.yaml" "$api_target"
  write_runtime_package_json "${STAGING_DIR}/package.json"

  log "Installing production Node dependencies in staging bundle"
  (cd "${STAGING_DIR}" && npm install --omit=dev --no-fund --no-audit)
}

prepare_full_sync_path() {
  local api_target="$1"
  [[ -f "${UI_DIR}/dist/cluster-advisor-ui/index.html" ]] \
    || die "Missing UI build output — run build first (or unset SKIP_BUILD)"

  if [[ -n "${API_PROXY_TARGET:-}" ]]; then
    log "Writing API_PROXY_TARGET into ${UI_DIR}/app.yaml for full sync"
    write_app_yaml "${UI_DIR}/app.yaml" "$api_target"
  fi

  printf '%s' "${UI_DIR}"
}

ensure_app_exists() {
  if databricks_cmd apps get "$APP_NAME" >/dev/null 2>&1; then
    log "Databricks app '${APP_NAME}' already exists"
    return 0
  fi
  if [[ "${CREATE_APP}" != "1" ]]; then
    die "App '${APP_NAME}' not found. Create it in the workspace UI or re-run with CREATE_APP=1"
  fi
  log "Creating Databricks app '${APP_NAME}'"
  databricks_cmd apps create "$APP_NAME"
}

main() {
  case "${1:-}" in
    -h|--help) usage 0 ;;
  esac

  require_cmd databricks
  require_cmd node
  require_cmd npm

  [[ -d "${UI_DIR}" ]] || die "UI directory not found: ${UI_DIR}"

  local api_target="${API_PROXY_TARGET:-}"
  if [[ -z "$api_target" ]]; then
    api_target="$(read_api_target_from_app_yaml "${UI_DIR}/app.yaml" || true)"
  fi
  [[ -n "$api_target" ]] || die "Set API_PROXY_TARGET to your FastAPI Databricks App URL (no trailing slash)"
  api_target="$(normalize_api_url "$api_target")"

  if [[ -z "${UI_WS_PATH:-}" ]]; then
    [[ -n "${WORKSPACE_USER:-}" ]] \
      || die "Set WORKSPACE_USER or UI_WS_PATH for the workspace sync destination"
    UI_WS_PATH="/Workspace/Users/${WORKSPACE_USER}/${APP_NAME}"
  fi
  # Normalize: must be a Databricks workspace path, not a Git-Bash-mangled local path
  if [[ "${UI_WS_PATH}" == *"/Program Files/Git/Workspace/"* ]]; then
    UI_WS_PATH="/Workspace/${UI_WS_PATH#*/Program Files/Git/Workspace/}"
    log "Corrected Git Bash workspace path to: ${UI_WS_PATH}"
  fi
  if [[ "${UI_WS_PATH}" != /Workspace/* ]]; then
    die "UI_WS_PATH must start with /Workspace/ (got: ${UI_WS_PATH}). On Git Bash use PowerShell or re-run this script (MSYS path fix is applied)."
  fi

  log "App name:        ${APP_NAME}"
  log "API proxy target: ${api_target}"
  log "Workspace path:  ${UI_WS_PATH}"
  log "Deploy mode:     ${DEPLOY_MODE}"

  if [[ "${SKIP_BUILD}" != "1" ]]; then
    log "Building Angular UI (npm ci && npm run build)"
    (cd "${UI_DIR}" && npm ci && npm run build)
  else
    log "Skipping UI build (SKIP_BUILD=1)"
  fi

  local sync_source
  case "${DEPLOY_MODE}" in
    slim)
      prepare_slim_bundle "$api_target"
      sync_source="${STAGING_DIR}"
      ;;
    full)
      sync_source="$(prepare_full_sync_path "$api_target")"
      ;;
    *)
      die "Invalid DEPLOY_MODE=${DEPLOY_MODE} (use slim or full)"
      ;;
  esac

  ensure_app_exists

  if [[ "${SKIP_SYNC}" != "1" ]]; then
    log "Syncing ${sync_source} -> ${UI_WS_PATH}"
    databricks_cmd sync "${sync_source}" "${UI_WS_PATH}"
  else
    log "Skipping sync (SKIP_SYNC=1)"
  fi

  log "Deploying Databricks app '${APP_NAME}'"
  databricks_cmd apps deploy "$APP_NAME" --source-code-path "${UI_WS_PATH}"

  log "Done. Check status and URL:"
  printf '  databricks apps get %s\n' "$APP_NAME"
  printf '  databricks apps logs %s\n' "$APP_NAME"
}

main "$@"
